<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Build tooling -->
  <ItemGroup>
    <PackageVersion Include="MinVer" Version="6.0.0" />
  </ItemGroup>

  <!-- Runtime (Abstractions) -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Core"      Version="2.3.0" />
    <PackageVersion Include="Microsoft.Extensions.Http"          Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options"       Version="10.0.0" />
  </ItemGroup>

  <!-- Test packages -->
  <ItemGroup>
    <PackageVersion Include="coverlet.collector"        Version="6.0.4"   />
    <PackageVersion Include="coverlet.msbuild"          Version="6.0.4"   />
    <PackageVersion Include="FluentAssertions"          Version="7.2.0"   />
    <PackageVersion Include="Microsoft.NET.Test.Sdk"    Version="17.14.1" />
    <PackageVersion Include="PublicApiGenerator"        Version="11.4.6"  />
    <PackageVersion Include="Verify.Xunit"              Version="28.16.0" />
    <PackageVersion Include="xunit"                     Version="2.9.3"   />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4"   />
  </ItemGroup>

</Project>
