<Project>
  <PropertyGroup>
    <Authors>MyCompany.External.Apis</Authors>
    <Company>MyCompany.External.Apis</Company>
    <PackageOutputPath>$(MSBuildThisFileDirectory)artifacts\</PackageOutputPath>
    <RepositoryType>git</RepositoryType>

    <MinVerTagPrefix>MyCompany.External.Apis/v</MinVerTagPrefix>
    <MinVerAutoIncrement>minor</MinVerAutoIncrement>
    <MinVerDefaultPreReleaseIdentifiers>alpha.0</MinVerDefaultPreReleaseIdentifiers>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <CopyDebugSymbolFilesFromPackages>true</CopyDebugSymbolFilesFromPackages>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MinVerVersion)' != ''">
    <Version>$(MinVerVersion)</Version>
    <PackageVersion>$(MinVerPackageVersion)</PackageVersion>
    <AssemblyVersion>$(MinVerAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(MinVerFileVersion)</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>
</Project>
